name: remote ssh command
on:
  push:
    branches:
      - development
jobs:
  build:
    name: DeployDSM
    runs-on: ubuntu-latest
    steps:
    - name: Execute SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_HOST }}
        username: ${{ secrets.DEV_USERNAME }}
        key: ${{ secrets.DEV_KEY }}
        passphrase: ${{ secrets.DEV_PASSPHRASE }}
        script: sh DeployDSM.sh
